// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvuspqkfhulbhgbryyvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dXNwcWtmaHVsYmhnYnJ5eXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNTI4OTQsImV4cCI6MjA5MTcyODg5NH0._U7UVzHo84-LwELamIGclRixgmbAEtDmDa9c07vreBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: typeof window !== "undefined",
    autoRefreshToken: true,
  }
});